---
- name: Compute Engine Instance 
  hosts: localhost
  vars:
#    service_account_email: "your-sa@your-project-name.iam.gserviceaccount.com"
    credentials_file: "k8s-key.json"
    project_id: "k8s-prod"
  tasks:
    - name: create multiple instances
      # Basic provisioning example.  Create multiple ubuntu instances in the
      gce:
        instance_names: master,node1,node2
        zone: us-central1-a
        machine_type: n1-standard-1
        image: ubuntu
        state: present
#        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        metadata : '{ "startup-script" : "apt-get update" }'
      register: gce

    - name: Save host data
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: gce_instances_ips
      with_items: "{{ gce.instance_data }}"

    - name: Wait for SSH for instances
      wait_for:
        delay: 1
        host: "{{ item.public_ip }}"
        port: 22
        state: started
        timeout: 30
      with_items: "{{ gce.instance_data }}"

    - name: Configure Hosts
      hosts: gce_instances_ips
      become: yes
      become_method: sudo
      roles:
        - my-role-one
        - my-role-two
      tags:
        - config

